test: test.cpp
	clang++ -std=c++11 test.cpp -o test
	./test

bellmanFord: bellmanFord.cpp
	clang++ -std=c++11 bellmanFord.cpp -o bellmanFord
	./bellmanFord < input_bellmanFord.txt

clean:
	rm -rf bellmanFord
