test5: test5.cpp
	clang++ -std=c++11 test5.cpp -o test5
	./test5

test4: test4.cpp
	clang++ -std=c++11 test4.cpp -o test4
	./test4

test3: test3.cpp
	clang++ -std=c++11 test3.cpp -o test3
	./test3 pi.txt
test1: test1.cpp
	clang++ -std=c++11 test1.cpp -o test1 -lpthread
	./test1

fancyOutput: fancyOutput.cpp
	clang++ -std=c++11 fancyOutput.cpp -o fancyOutput
	./fancyOutput

clean:
	rm -rf test test1 test2 fancyOutput
